### ISSUE TITLE
LED & Switch pins

### ISSUE THREAD

**Issue by iqrohan** [iquesters/iqwsiot_firmware#10]
LED enum to be changed in bsp as per dev board
Additional switches to be deleted

**Comment by noyelseth** [comment]
LED enum changed in bsp as per dev board & delete Additional Switch #10
51615a91142e7ba964abcf3aefa91edc4ce847a3

**Comment by iqrohan** [comment]
Issue is not closed as the code changes done has compilation error.

Also in bsp_harmony.c line 256 the function name has been changed from PLIB_PORTS_PinGetLatched to PLIB_PORTS_PinGet. Unrequited code changes made in notification.c & bsp_harmony.c

Please ensure everything gets reverted & fixed ASAP.

**Comment by noyelseth** [comment]
LED enum changed in bsp as per 'iqwsiot' dev board as 'IQ_BSP_LED_x' & delete Additional switches

8719a376ba2f10535325debd71a52eebf1942116
