### ISSUE TITLE
GSM SIM800 device ack error handling in app

### ISSUE THREAD

**Issue by iqrohan** [iquesters/iqwsiot_firmware#12]
Error handling for ACK Error to be done in:
switch (appData.app_error.gsm_error) {
    case GSM_ERROR_DEV_ACK:
}

**Comment by noyelseth** [comment]
ef9879b2b77c677b530bb190262c18e7a22fca16

Solve GSM module's USART Error bug 'GSM_ERROR_USART', 'GSM_ERROR_DEV_ACK' Error bug

**Comment by iqrohan** [comment]
Reviewed.
