### ISSUE TITLE
GPS module's USART Error bug

### ISSUE THREAD

**Issue by iqrohan** [iquesters/iqwsiot_firmware#15]
GPS module to remain in GPS_IDLE state when not in use after a USART error occurs.
Bug to be fixed by making the gps module's tasks as per sim800 gsm & http module.

**Comment by noyelseth** [comment]
ef9879b2b77c677b530bb190262c18e7a22fca16
Fix GPS module's USART Error bug #15 & Additional 'GSM_ERROR_USART', 'GSM_ERROR_DEV_ACK' Error bug at APP_HANDLE_ERROR
