### ISSUE TITLE
Memory Leak in tokenize_response

### ISSUE THREAD

**Issue by iqrohan** [iquesters/iqwsiot_firmware#18]
Memory Leak in tokenize_response in gsm_sim800_utility.c to be fixed

**Comment by noyelseth** [comment]
Memory Leak comes from, gsm_sim800_utility.c, in tokenize_response(char* ack_str) function line number 146/147 at for memory allocation for response token by malloc,

**Comment by noyelseth** [comment]
In  gsm_sim800_utility.c, of gsm_sim800_utility_clear_msgs(), there is a mistake in logic to free all allocated tokenize_response that is, 
if (response.msg_idx > 0){
        for (response.msg_idx; response.msg_idx > 0; response.msg_idx--) {
            free(response.msg[response.msg_idx]);
        }
    }
______________________________________________________________________________________________
here is he solve, 
if (response.msg_idx >= 0){
        for (response.msg_idx; response.msg_idx >= 0; response.msg_idx--) {
            free(response.msg[response.msg_idx]);
        }
    }
and it committed at ID - cbd08076163a035496f6f88e39d25732e6880938
