### ISSUE TITLE
SIM CARD Inserted or not checking

### ISSUE THREAD

**Issue by iqrohan** [iquesters/iqwsiot_firmware#27]
In function "parse_sim_card_present_status_ack" logic does not check for ""+CSMINS: 0,0" i.e. if sim card is not present

If the SIM Card is not present the function will return "false", but this does not signifies whether it is a parse error or SIM card is actually not present

**Comment by noyelseth** [comment]
Now parse_sim_card_present_status_ack return 1 if sim present otherwise 2. if ACK is invalid then return 0

05f007a124fae65e0163c4d8ee0cd42d3cd1bde7
