### ISSUE TITLE
APN auto detection

### ISSUE THREAD

**Issue by iqrohan** [iquesters/iqwsiot_firmware#28]
APN is hardcoded as of now. APN matrix has to be made in the GSM Library and should be detected as per Service Provider

**Comment by noyelseth** [comment]
Lib get the Provider name from Sim and then compare that name and collect the APN, USER_ID, PWD. After that Lib Use these APN, USER_ID, PWD by calling
gsm_sim800_common_get_gprs_apn();
gsm_sim800_common_get_gprs_user_id();
gsm_sim800_common_get_gprs_pwd(); 

05f007a124fae65e0163c4d8ee0cd42d3cd1bde7
