### ISSUE TITLE
Project Configuration error - Logger.c file not found

### ISSUE THREAD

**Issue by iqrohan** [iquesters/iqwsiot_firmware#29]
Logger.c file is not pushed to git server.

**Comment by noyelseth** [comment]
![image](https://user-images.githubusercontent.com/29272159/30771408-d88727c6-a064-11e7-97bd-04ec2d8f89cd.png)
 I already pushed Logger.c in last commite 597465d0d8c4a2e27ba845d77182cb0ef8dec1d0

**Comment by noyelseth** [comment]
logger.c pushed in commit id -> 63b7c9c58ce07dcd10102f53604e3fc18883f5ea
