### ISSUE TITLE
SD Card & LED notification for debugging field testing issues

### ISSUE THREAD

**Issue by iqrohan** [iquesters/iqwsiot_firmware#30]
1. Switch for configuring USART Log or SD Log or both
2. LED notification for run-time exceptions

The objective is to identify firmware hanging issue.

**Comment by noyelseth** [comment]
e4538d0b78ba4454dd4059f13ba17392efbf1855   = LED notification for run-time exceptions

63b7c9c58ce07dcd10102f53604e3fc18883f5ea  =  Switch for configuring USART Log or SD Log or both
