### ISSUE TITLE
Sensor Integration: Temperature, Humidity & Lock

### ISSUE THREAD

**Issue by iqrohan** [iquesters/iqwsiot_firmware#4]
These 3 sensors should communicate with Harmony through bsp_harmony.c/.h files
Each sensor must have a file for itself like ds18b20.c/.h etc.

Implement hardware related code for these in bsp_harmony.c/.h

For lock sensor there should be a callback notifier to the application.

**To be completed by: 18/07/2017**

**Comment by iqrohan** [comment]
@noyelseth 
Sensor bugs to be fixed:
1. ADC read without delay
2. EXT INT enable & disable

**Comment by iqrohan** [comment]
Issue Label changed to bug

**Comment by noyelseth** [comment]
cffef4d554fe999a7939c0f6dbea18792e40571c

Fix Bug "ADC read without delay" #4

changing the logic of "while (bsp_harmony_adc_samples_available() != true);        // wait for ADC conversion complete." from "while (bsp_harmony_adc_samples_available() == true);"

**Comment by noyelseth** [comment]
4bc4b1889b622e83a536242c395c3d79059d731b

Fix EXT INT enable & disable for LOCK_Device

**Comment by noyelseth** [comment]
Error and validation & status handling Issue #16 & #13
LOCK_Error handling also done in this commit
40a62e022752413bf057d62a480f08664c074e47
