### ISSUE TITLE
Device authentication

### ISSUE THREAD

**Issue by iqsam** [iquesters/iqwsiot_firmware#6]
Refer to:
2.3.	Embedded
2.3.1.	Authentication Service

**Comment by iqrohan** [comment]
Device versioning (HW+FW), configurations (for sensors and interfaces) & COM port based program needed for Offline Preauth.
Preauth needs to be done before Device Authentication.

Basic level of versioning and configurations integrated. TODO integration of COM port based program with this app.

**Comment by iqrohan** [comment]
Device Authentication implemented. Both SUCCESS & FAILURE case are tested with server.
